services:
  mongodb:
    image: mongo:6.0
    container_name: skillswap-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
